<?php

namespace Tests\Browser;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class BlockPageTest extends DuskTestCase
{
    public function testSpecificBlock()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/blocks/7271bb29b4af62a5a5841e0f10844123803843e139a84601b418697b40e1f5ca')
                    ->assertSee('7271bb29b4af62a5a5841e0f10844123803843e139a84601b418697b40e1f5ca')
                    ->assertSee('Generated by')
                    ->assertSee('thefoundry');
        });
    }
}
