@php
    /**
    * @var $paginator Illuminate\Pagination\LengthAwarePaginator;
    * @var $items \Ark\Domain\Blocks\BlockModel[];
    */
    $items = $paginator->items();
@endphp

@if( $paginator->count() === 0 )
    <div class="bg-blue-100 border-t border-b border-blue-500 text-blue-700 px-4 py-3" role="alert">
        <p class="font-bold">No data available</p>
    </div>
@else
<div class="bg-gray-100">
    <div class="loadingOverlay" wire:loading>
        <div class="spinner"></div>
    </div>

    <table class="min-w-full table-auto">
        <thead>
        <tr>
            <th class="table-header-row">Id</th>
            <th class="table-header-row">Height</th>
            <th class="table-header-row">Timestamp</th>
            <th class="table-header-row">Transactions</th>
            <th class="table-header-row">Generated by</th>
            <th class="table-header-row">Total forged</th>
            <th class="table-header-row">Fees</th>
        </tr>
        </thead>
        <tbody class="bg-white">
        @foreach($items as $i)
            @include('alpine.blockRow',['block' => $i])
        @endforeach
        </tbody>
    </table>

    <div class="livewire-pagination mt-3">
        {{$paginator->links()}}
    </div>
</div>
@endif
