<?php
/**
 * @var $block \Ark\Domain\Blocks\BlockModel
 */

?>

<div
    x-data="setup()"
>
    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">
            Transactions
        </p>
        <p class="text-gray-500">
            {{ $block->getTransactions() }}
        </p>
    </div>
    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">
            Confirmations
        </p>
        <div class="text-gray-500">
            @livewire('block-confirmations',['blockHeight'=>$block->getHeight(),'blockConfirmations'=>$block->getConfirmations()])
        </div>
    </div>
    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">
            Height
        </p>
        <p class="text-gray-500">
            {{ $block->getHeight() }}
        </p>
    </div>
    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">
            Reward
        </p>
        <p class="text-gray-500">
            <span x-text="ArkApp.helpers.readableCurrency(reward)"></span>
        </p>
    </div>
    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">Fees</p>
        <p class="text-gray-500">
            <span x-text="ArkApp.helpers.readableCurrency(fees)"></span>
        </p>
    </div>
    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">Total forged</p>
        <p class="text-gray-500">
            <span x-text="ArkApp.helpers.readableCurrency(totalForged)"></span>
        </p>
    </div>
    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">
            Processed amount
        </p>
        <p class="text-gray-500">
            <span x-text="ArkApp.helpers.readableCurrency(totalForged)"></span>
        </p>
    </div>
    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">
            Timestamp
        </p>
        <p class="text-gray-500">
            {{ \Carbon\Carbon::parse($block->getTimestamp()['unix']) }}
        </p>
    </div>

    <div class="flex justify-between px-2 py-2 text-lg border-b-2 border-gray-200">
        <p class="flex">
            Generated by
        </p>
        <p class="text-gray-500">
            <a class="text-blue-500 hover:text-blue-900 font-semibold"
               href="{{ route('wallet.detail',['id'=>$block->getGenerator()->getAddress()]) }}">
                {{ $block->getGenerator()->getUsername() }}
            </a>
        </p>
    </div>
</div>

<script>
    function setup() {
        return {
            id: '{{ $block->getId() }}',
            reward: '{{ $block->getReward() }}',
            fees: '{{ $block->getFee() }}',
            totalForged: '{{ $block->getTotalForged() }}',
            amount: '{{ $block->getAmount() }}'
        }
    }
</script>
